import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Agent worktrees are full checkouts nested inside the repo, so their build
    // output would otherwise be linted: the default ".next/**" pattern is
    // anchored at the root and does not match a nested one.
    ".claude/**",
    // Generated by e2e runs.
    "playwright-report/**",
    "test-results/**",
  ]),
]);

export default eslintConfig;
